Update build-haiku.yml

diff --git a/.github/workflows/build-haiku.yml b/.github/workflows/build-haiku.yml
--- a/.github/workflows/build-haiku.yml
+++ b/.github/workflows/build-haiku.yml
@@ -52,6 +52,12 @@ jobs:
             ./build.sh --clean-while-building --prep -sb --os ${{ matrix.name }} --rid ${{ matrix.name }}-x64 \
               --arch x64 ${{ inputs.is_rtm && '--branding rtm' || '' }} -p:OfficialBuildId=$(date +%Y%m%d).99
 
+    - name: Dump runtime log on failure
+      if: failure()
+      run: |
+        echo "=== runtime.log ==="
+        cat ${{ github.workspace }}/dotnet/artifacts/log/Release/runtime/runtime.log || echo "log not found"
+
     - name: List assets directory
       run: |
         find "${{ github.workspace }}/dotnet/artifacts"
